### ISSUE TITLE
CI to Publish SubQuery project to IPFS

### ISSUE THREAD

**Issue by ccamel** [okp4/subql-okp4#3]
## Proposal

To enable the deployment of the project on [SubQuery's Managed Service](https://project.thechaindata.com) (if we want to), it is required to host the project codebase on [IPFS](https://ipfs.tech/). In order to achieve this, we propose implementing a `publish` GitHub workflow that will automate the deployment of the codebase on [IPFS](https://ipfs.tech/).

## Tasks

- [ ] Develop and implement a `publish` GitHub workflow tailored specifically to host the codebase on [IPFS](https://ipfs.tech/), operating on the `main` branch.
- [ ] Possibly mention this publication in `README.md` documentation file.
- [ ] Reference the workflow to the [okp4/actions](https://github.com/okp4/actions/tree/main/src/.github/workflows) repository.

## Resources

- https://academy.subquery.network/run_publish/publish.html#publish-your-subquery-project-to-ipfs
- https://github.com/parallel-finance/relaychain-subql/blob/f765961a86ad293762e27eadf9464cde52d7e81b/.github/workflows/deploy.yml#L31
