### ISSUE TITLE
Add a job to report graphQL schema changes upon PR

### ISSUE THREAD

**Issue by ccamel** [okp4/subql-okp4#6]
## Idea

Every time the graphQL schemas change, we need to be informed if the change is  breaking or non-breaking. 

## Proposal

The proposal is to automatically post a comment on the PR whenever there are modifications to the GraphQL schemas. This comment will provide information about whether the changes are breaking or non-breaking.

To implement this, we can use the [actions/graphql-inspector](https://github.com/marketplace/actions/graphql-inspector) GitHub action, which will take care of the inspection of the schemas when the PR is opened.

## Todo

- [ ] Assess the suitability of [actions/graphql-inspector](https://github.com/marketplace/actions/graphql-inspector) for our requirements.
- [ ] Implement a new job in the `lint` workflow responsible for posting a descriptive comment regarding any changes made to the GraphQL schemas.
- [ ] Conduct testing to ensure the functionality works as intended.
